### ISSUE TITLE
KucoinAPIException 400003: KC-API-KEY not exists

### ISSUE THREAD

**Issue by salehirandom** [Kucoin/kucoin-python-sdk#125]
I got error on creating market order, here is the details:

```bash
$ pip freeze| grep -i kucoin
kucoin-python==1.0.25
python-kucoin==2.2.0
```

```python
from kucoin.client import Client

proxies = {
    'http': 'http://127.0.0.1:7890',
    'https': 'http://127.0.0.1:7890',
}
KUCOIN_SECRET_KEY = "..."
KUCOIN_API_KEY = "..."
KUCOIN_PASSPHRASE = "..."

client = Client(
    KUCOIN_API_KEY,
    KUCOIN_SECRET_KEY,
    KUCOIN_PASSPHRASE,
    requests_params={
        "verify": False,
        "timeout": 20,
        'proxies': proxies
    }
)

order = client.create_market_order('TRX-USDT', client.SIDE_BUY, funds='5.000', client_oid="salehitest")
print(order)

```

I got the following error:
```txt
/tmp/proof/venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/tmp/proof/proof.py", line 26, in <module>
    order = client.create_market_order('TRX-USDT', client.SIDE_BUY, funds='5.000', client_oid="salehitest")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/proof/venv/lib/python3.12/site-packages/kucoin/client.py", line 4363, in create_market_order
    return self.create_order(
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/proof/venv/lib/python3.12/site-packages/kucoin/client.py", line 4313, in create_order
    return self._post("orders", True, data=dict(data, **params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/proof/venv/lib/python3.12/site-packages/kucoin/base_client.py", line 204, in _post
    return self._request("post", path, signed, api_version, is_futures, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/proof/venv/lib/python3.12/site-packages/kucoin/base_client.py", line 172, in _request
    return self._handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/proof/venv/lib/python3.12/site-packages/kucoin/base_client.py", line 182, in _handle_response
    raise KucoinAPIException(response, response.status_code, response.text)
kucoin.exceptions.KucoinAPIException: KucoinAPIException 400003: KC-API-KEY not exists

Process finished with exit code 1

```

Here is the repo if you want to do it yourself:
https://github.com/salehirandom/kucoin-proof/

Help me!

**Comment by salehirandom** [comment]
I found out that the value of secret_key and api_key are misplaced!
Thats it
