### ISSUE TITLE
[ERROR] AttributeError: 'dict' object has no attribute 'encode'

### ISSUE THREAD

**Issue by SuprGrobi** [Kucoin/kucoin-python-sdk#39]
[ERROR] AttributeError: 'dict' object has no attribute 'encode'Traceback (most recent call last):  

File "/var/task/kucoin_.py", line 32, in handler    lending_market = margin.get_lend_record()  File "/var/task/kucoin/margin/margin.py", line 384, in get_lend_record    return self._request('GET', '/api/v1/margin/lend/assets', params=params)  File "/var/task/kucoin/base_request/base_request.py", line 65, in _request    hmac.new(self.secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest()) | [ERROR] AttributeError: 'dict' object has no attribute 'encode' Traceback (most recent call last):   File "/var/task/kucoin_lambda.py", line 32, in lambda_handler     lending_market = margin.get_lend_record()   File "/var/task/kucoin/margin/margin.py", line 384, in get_lend_record     return self._request('GET', '/api/v1/margin/lend/assets', params=params)   File "/var/task/kucoin/base_request/base_request.py", line 65, in _request     hmac.new(self.secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest())

**Comment by SuprGrobi** [comment]
better presentation:

[ERROR] AttributeError: 'dict' object has no attribute 'encode'
Traceback (most recent call last):
  File "/var/task/kucoin_lambda.py", line 32, in lambda_handler
    lending_market = margin.get_lend_record()
  File "/var/task/kucoin/margin/margin.py", line 384, in get_lend_record
    return self._request('GET', '/api/v1/margin/lend/assets', params=params)
  File "/var/task/kucoin/base_request/base_request.py", line 65, in _request
    hmac.new(self.secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest())

**Comment by ISAAC-XXYYZZ** [comment]
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
