### ISSUE TITLE
create_market_order fails with "Funds increment invalid."

### ISSUE THREAD

**Issue by ygpedroso** [Kucoin/kucoin-python-sdk#55]
I've coded a bot to track cryptos and execute trades on my behalf when the time is right. However, every time it tries to perform a market order "buy" it fails with the following error.

```
ERROR:root:Failed to execute buy.
2022-01-19T03:56:25.573860+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-19T03:56:25.573860+00:00 app[worker.1]:   File "main.py", line 47, in _execute_buy
2022-01-19T03:56:25.573861+00:00 app[worker.1]:     order_id = api.buy(crypto_pair, buy_amount)
2022-01-19T03:56:25.573861+00:00 app[worker.1]:   File "/app/lib/api.py", line 80, in buy
2022-01-19T03:56:25.573862+00:00 app[worker.1]:     response = trade_client.create_market_order(
2022-01-19T03:56:25.573864+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/kucoin/trade/trade.py", line 164, in create_market_order
2022-01-19T03:56:25.573865+00:00 app[worker.1]:     return self._request('POST', '/api/v1/orders', params=params)
2022-01-19T03:56:25.573865+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 99, in _request
2022-01-19T03:56:25.573865+00:00 app[worker.1]:     return self.check_response_data(response_data)
2022-01-19T03:56:25.573866+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 116, in check_response_data
2022-01-19T03:56:25.573867+00:00 app[worker.1]:     raise Exception("{}-{}".format(response_data.status_code, response_data.text))
2022-01-19T03:56:25.573867+00:00 app[worker.1]: Exception: 200-{"code":"400100","msg":"Funds increment invalid."}
```

Even though the API document says that the price increment is not required for marker orders: https://docs.kucoin.com/#place-a-new-order

Could anyone assist with this issue?
This is how my buying code looks using the library:

```
import uuid
from kucoin.client import Trade

trade_client = Trade(
    settings.API_KEY,
    settings.API_SECRET,
    settings.API_PASSPHRASE,
    is_sandbox=False,
)

def buy(symbol: strr, amount: float) -> str:
    """Buy a crypto-pair."""
    client_order_id = str(uuid.uuid4())
    response = trade_client.create_market_order(
        symbol,
        "buy",
        clientOid=client_order_id,
        type="market",
        funds=str(amount),
    )
   return response["orderId"]
```

**Comment by herokuprojects666** [comment]
You need to ensure that the value you pass through is rounded according to baseIncrement or quoteIncrement (depending on whether you are passing in size or funds argument). This can be fetched using the API defined here: https://docs.kucoin.com/#get-symbols-list

To give you an example:

Let's say that you were buying ADA-USDT and the quote increment is .01 and you were passing through the amount on funds key, the value you pass through must be an increment of .01. 
1.03 => good
1.034 => no good (should probably round down to ensure you have enough funds to buy it)

**Comment by ygpedroso** [comment]
> You need to ensure that the value you pass through is rounded according to baseIncrement or quoteIncrement (depending on whether you are passing in size or funds argument). This can be fetched using the API defined here: https://docs.kucoin.com/#get-symbols-list
> 
> To give you an example:
> 
> Let's say that you were buying ADA-USDT and the quote increment is .01 and you were passing through the amount on funds key, the value you pass through must be an increment of .01. 1.03 => good 1.034 => no good (should probably round down to ensure you have enough funds to buy it)

Thank you. That solved my problem.

**Comment by OlMi1** [comment]
> Let's say that you were buying ADA-USDT and the quote increment is .01 and you were passing through the amount on funds key, the value you pass through must be an increment of .01. 1.03 => good 1.034 => no good (should probably round down to ensure you have enough funds to buy it)

Sorry for posting on this issue again, but where do I get that from? For instance, the symbol list data for Monero is:
```
{
   "currency":"XMR",
   "name":"XMR",
   "fullName":"Monero",
   "precision":8,
   "confirms":12,
   "contractAddress":"",
   "withdrawalMinSize":"0.020000",
   "withdrawalMinFee":"0.001000",
   "isWithdrawEnabled":true,
   "isDepositEnabled":true,
   "isMarginEnabled":true,
   "isDebitEnabled":true
}
```

The value sent to kucoin (note the string quotes) is: `'0.01003226'`

Still, the server response is `{"code":"400100","msg":"Order size increment invalid."}`. What am I doing wrong here? It says `precision` is 8, and my number (sent as string) has a precision of 8.
