### ISSUE TITLE
Error Placing Market Order "code":"400003","msg":"KC-API-KEY not exists"

### ISSUE THREAD

**Issue by Mas313** [Kucoin/kucoin-python-sdk#80]
I am getting error on Market Trade like this : Error Placing Market Order "code":"400003","msg":"KC-API-KEY not exists"  .  My code is simple to test a buy order

```
from kucoin.client import Market
from kucoin.client import Trade
api_key = ''  
api_secret = ''
api_passphrase = ''
def buy():
   client = Market(url='https://api.kucoin.com')
   client = Trade(key=api_secret, secret=api_secret, passphrase=api_passphrase , is_sandbox=False, url='')
   order_id = client .create_market_order('ADA-USDT', 'buy', size='1') # also tested with type='market' parameter but no luck
   print(order_id)
#function call
buy()
```

The complete error looks as follows
```
Traceback (most recent call last):
  File "TradeTest.py", line 42, in <module>
    buy()
  File "TradeTest.py", line 38, in buy
    order_id = client .create_market_order('ADA-USDT', 'buy', size='1' , type='market')
  File "C:\Users\Masood\AppData\Local\Programs\Python\Python38\lib\site-packages\kucoin\trade\trade.py", line 164, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "C:\Users\Masood\AppData\Local\Programs\Python\Python38\lib\site-packages\kucoin\base_request\base_request.py", line 99, in _request
    return self.check_response_data(response_data)
  File "C:\Users\Masood\AppData\Local\Programs\Python\Python38\lib\site-packages\kucoin\base_request\base_request.py", line 118, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 401-{"code":"400003","msg":"KC-API-KEY not exists"}
```

**Comment by Mas313** [comment]
I wrongly put secret key in API key value
